[gh.workflow]
env_key = "ANTHROPIC_API_KEY"                # the env key must match the secret
model = "anthropic/claude-sonnet-4-20250514"

[opencode.commands]
# template = default | custom, if custom, the template_file must be specified
# The default template is in control/commands/generic/git-commit.md
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template

[opencode.commands.commit]
enabled = true
vcs = "git"
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"

[opencode.commands.worktrees]
enabled = true
vcs = "git"
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"

# include_base_template = true will include the base template in the additional_files
#  Path for base template is control/commands/generic/clean/base.md. lang = elixir | kotlin | typescript. more coming soon
# Lang additional template in control/commands/generic/clean/<lang>.md
[opencode.commands.clean]
enabled = true
lang = "elixir"
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true

# include_base_template = true will include the base template in the additional_files
#  Path for base template is control/commands/generic/test/base.md. lang = elixir | kotlin | typescript. more coming soon
# Lang additional template in control/commands/generic/test/<lang>.md
[opencode.commands.test]
enabled = true
lang = "elixir"
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true

# include_base_template = true will include the base template in the additional_files
#  Path for base template is control/commands/generic/optimizer/base.md. lang = elixir | kotlin | typescript. more coming soon
# Lang additional template in control/commands/generic/optimizer/<lang>.md
[opencode.commands.optimizer]
enabled = true
lang = "elixir"
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true

# template = default | custom, if custom, the template_file must be specified
# The default template is in control/commands/generic/prompter.md
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template
# include_base_template = true will include the base template in the additional_files
#  Path for base template is control/commands/generic/prompter/base.md
[opencode.commands.prompter]
enabled = true
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true

# template = default | custom, if custom, the template_file must be specified
# The default template is in control/commands/generic/context.md
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template
[opencode.commands.context]
enabled = true
agent = "build"
model = "anthropic/claude-sonnet-4-20250514"
template = "default"
template_file = ""
additional_files = [
]
additional_files_strategy = "merge"

[opencode.agents]
# Primary agents configuration section
# template = default | custom, if custom, the template_file must be specified
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template

[opencode.agents.codebase-agent]
enabled = true
template = "default"
additional_files = [
]
additional_files_strategy = "merge"
description = "Multi-language implementation agent for modular and functional development"
mode = "primary"
model = "anthropic/claude-sonnet-4-20250514"
temperature = 0.1

[opencode.agents.codebase-agent.permissions.tools]
read = true
edit = true
write = true
grep = true
glob = true
bash = true
patch = true

[opencode.agents.codebase-agent.permissions.bash_rules]
"*" = "allow"
"rm -rf *" = "ask"
"sudo *" = "deny"
"chmod *" = "ask"
"curl *" = "ask"
"wget *" = "ask"
"docker *" = "ask"
"kubectl *" = "ask"

[opencode.agents.codebase-agent.permissions.edit_rules]
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"
"node_modules/**" = "deny"
".git/**" = "deny"

[opencode.agents.task-manager]
enabled = true
template = "default"
additional_files = [
]
additional_files_strategy = "merge"
description = "Breaks down complex features into small, verifiable subtasks"
mode = "primary"
model = "anthropic/claude-sonnet-4-20250514"
temperature = 0.1

[opencode.agents.task-manager.permissions.tools]
read = true
edit = "ask"
write = true
grep = true
glob = true
bash = false
patch = true

[opencode.agents.task-manager.permissions.bash_rules]
"*" = "deny"

[opencode.agents.task-manager.permissions.edit_rules]
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"
"node_modules/**" = "deny"
".git/**" = "deny"

[opencode.agents.subagents]
# template = default | custom, if custom, the template_file must be specified
# The default template is in control/agents/debugger/base.md
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template
# include_base_template = true will include the base template in the additional_files
# lang = elixir | kotlin | typescript. more coming soon

[opencode.agents.subagents.debugger]
enabled = true
template = "default"
lang = "elixir"
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true
description = "Advanced debugging specialist human-friendly feedback"
mode = "subagent"
model = "anthropic/claude-sonnet-4-20250514"
temperature = 0.1

[opencode.agents.subagents.debugger.permissions.tools]
read = true
edit = true
write = false
grep = true
glob = true
patch = false
bash = true

[opencode.agents.subagents.debugger.permissions.bash_rules]
"rm -rf *" = "deny"
"sudo *" = "deny"
"mix *" = "allow"
"./gradlew *" = "allow"
"npm *" = "allow"
"yarn *" = "allow"
"git *" = "allow"

[opencode.agents.subagents.debugger.permissions.edit_rules]
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"
"**/*.pem" = "deny"
"node_modules/**" = "deny"
".git/**" = "deny"
"_build/**" = "deny"
"deps/**" = "deny"
"build/**" = "deny"

# Simple subagents (no lang support)
[opencode.agents.subagents.documentation]
enabled = true
template = "default"
additional_files = [
]
additional_files_strategy = "merge"
description = "Multi-language documentation authoring and maintenance agent"
mode = "subagent"
model = "google/gemini-2.5-flash"
temperature = 0.2

[opencode.agents.subagents.documentation.permissions.tools]
read = true
grep = true
glob = true
edit = true
write = true
bash = false

[opencode.agents.subagents.documentation.permissions.bash_rules]
"*" = "deny"

[opencode.agents.subagents.documentation.permissions.edit_rules]
"**/*.md" = "allow"
"docs/**/*" = "allow"
"README*" = "allow"
"**/CHANGELOG*" = "allow"
"plan/**/*.md" = "allow"
"**/*.adoc" = "allow"
"**/*.rst" = "allow"
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"
"**/*.pem" = "deny"
"node_modules/**" = "deny"
".git/**" = "deny"
"_build/**" = "deny"
"deps/**" = "deny"
"build/**" = "deny"
".gradle/**" = "deny"
"dist/**" = "deny"

[opencode.agents.subagents.reviewer]
enabled = true
template = "default"
additional_files = [
]
additional_files_strategy = "merge"
description = "Code review, security, and quality assurance agent"
mode = "subagent"
model = "anthropic/claude-sonnet-4-20250514"
temperature = 0.1

[opencode.agents.subagents.reviewer.permissions.tools]
read = true
grep = true
glob = true
bash = false
edit = false
write = false

[opencode.agents.subagents.reviewer.permissions.bash_rules]
"*" = "deny"

[opencode.agents.subagents.reviewer.permissions.edit_rules]
"**/*" = "deny"

[opencode.agents.subagents.tester]
enabled = true
template = "default"
additional_files = [
]
additional_files_strategy = "merge"
description = "Test authoring and TDD agent"
mode = "subagent"
model = "google/gemini-2.5-flash"
temperature = 0.1

[opencode.agents.subagents.tester.permissions.tools]
read = true
grep = true
glob = true
edit = true
write = true
bash = true

[opencode.agents.subagents.tester.permissions.bash_rules]
"rm -rf *" = "ask"
"sudo *" = "deny"

[opencode.agents.subagents.tester.permissions.edit_rules]
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"

# Multi-language subagents (with lang support)
[opencode.agents.subagents.code-pattern-analyst]
enabled = true
template = "default"
lang = "elixir"
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true
description = "Multi-language pattern codebase"
mode = "subagent"
model = "google/gemini-2.5-flash"
temperature = 0.1

[opencode.agents.subagents.code-pattern-analyst.permissions.tools]
read = true
grep = true
glob = true
bash = false
edit = false
write = false

[opencode.agents.subagents.code-pattern-analyst.permissions.bash_rules]
"*" = "deny"

[opencode.agents.subagents.code-pattern-analyst.permissions.edit_rules]
"**/*" = "deny"

[opencode.agents.subagents.coder-agent]
enabled = true
template = "default"
lang = "elixir"
additional_files = [
]
additional_files_strategy = "merge"
include_base_template = true
description = "Executes coding subtasks in sequence, ensuring completion as specified"
mode = "subagent"
model = "anthropic/claude-sonnet-4-20250514"
temperature = 0

[opencode.agents.subagents.coder-agent.permissions.tools]
read = true
edit = true
write = true
grep = true
glob = true
bash = true
patch = true

[opencode.agents.subagents.coder-agent.permissions.bash_rules]
"*" = "allow"
"rm -rf *" = "ask"
"rm -rf **" = "ask"
"sudo *" = "ask"

[opencode.agents.subagents.coder-agent.permissions.edit_rules]
"**/*.env*" = "deny"
"**/*.key" = "deny"
"**/*.secret" = "deny"
"**/*.pem" = "deny"
"node_modules/**" = "deny"
".git/**" = "deny"
"_build/**" = "deny"
"deps/**" = "deny"
"build/**" = "deny"
".gradle/**" = "deny"
"dist/**" = "deny"
"config/prod.secret.exs" = "deny"
"config.toml" = "deny"
"**/*.keystore" = "deny"
"**/*.jks" = "deny"
