[gh.workflow]
env_key = "ANTHROPIC_API_KEY"                # the env key must match the secret
model = "anthropic/claude-sonnet-4-20250514"

[opencode.commands]
# template = default | custom, if custom, the template_file must be specified
# The default template is in control/commands/generic/git-commit.md
# additional_files is a list of files to be included/passed to llm
# additional_files_strategy = merge | replace, if merge, the additional_files will be merged with the template, if replace, the additional_files will replace the template
commit = { enabled = true, vcs = "git", agent = "build", model = "anthropic/claude-sonnet-4-20250514", template = "default", template_file = "", additional_files = [], additional_files_strategy = "merge" }

worktrees = { enabled = true, vcs = "git", agent = "build", model = "anthropic/claude-sonnet-4-20250514", template = "default", template_file = "", additional_files = [], additional_files_strategy = "merge" }
